# Generated by Django 5.0 on 2025-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_drive_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_drive_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
