# Generated by Django 5.0 on 2025-11-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_google_drive_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.TextField(blank=True, default='https://example.com/default_logo.png', null=True),
        ),
    ]
