# Generated by Django 5.0 on 2025-11-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_sharelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='node',
        ),
        migrations.AddField(
            model_name='sharelink',
            name='file_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
