# Generated by Django 5.0 on 2025-10-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='media_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
